
service:
  name: brainy-auth-demo

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  apiGateway: ${file(../../config/serverless.env.yml):${opt:stage}.apiGateway}
  role: arn:aws:iam::970663928408:role/awsLambdaRoleFull
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 7 #
  stackTags:
    APP:  "BRAINY-DEV"
    MODULE: "AUTH-LOGIN"
  environment:
      NODE_ENV: ${file(../../config/serverless.env.yml):${opt:stage}.NODE_ENV}

functions:
  login:
    handler: handler.login
    tags:
      action: post
    events:
      - http:
          method: post
          path: /auth-login-demo
          cors: true
