service:
  name: brainy-auth

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  apiGateway: ${file(../../config/serverless.env.yml):${opt:stage}.apiGateway}
  role: arn:aws:iam::970663928408:role/awsLambdaRoleFull
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 7 #
  stackTags:
    APP:  "BRAINY"
    MODULE: "AUTHENTICATION"
  environment:
      NODE_ENV: ${file(../../config/serverless.env.yml):${opt:stage}.NODE_ENV}

functions:
  sign-up:
    handler: handler.signUp
    events:
      - http:
          method: post
          path: /auth/signup
          cors: true
  confirm:
    handler: handler.confirm
    events:
      - http:
          method: post
          path: /auth/confirm
          # authorizer:
          #   type: CUSTOM
          #   authorizerId: bh5l1b
          cors: true
  signIn:
    handler: handler.signIn
    events:
      - http:
          method: post
          path: /auth/signin
          # authorizer:
          #   type: CUSTOM
          #   authorizerId: bh5l1b
          cors: true
  forgotten-password:
    handler: handler.forgottenPassword
    events:
      - http:
          method: post
          path: /auth/forgotten-password
          cors: true
  change-password:
    handler: handler.changePassword
    events:
      - http:
          method: post
          path: /auth/change-password
          cors: true
  authorizer:
    handler: handler.authorizer
