service:
  name: email

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

functions:
  send:
    handler: Email.send
environment:
      BUCKET_NAME: brainy-img
      

