service:
  name: brainy-core-floting-note

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2

functions:
  save:
    handler: handler.save
  update:
    handler: handler.update
  delete:
    handler: handler.erase
  get:
    handler: handler.get
  list:
    handler: handler.list


