service:
  name: brainy-thumb

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  role: arn:aws:iam::970663928408:role/awsLambdaRoleFull
  environment:
      NODE_ENV: ${file(./serverless.env.yml):${opt:stage}.NODE_ENV}

functions:
  create:
    handler: Thumbanail.createThumbnail
