service:
  name: brainy-project

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  apiGateway: ${file(../../config/serverless.env.yml):${opt:stage}.apiGateway}
  role: arn:aws:iam::970663928408:role/awsLambdaRoleFull
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 12 #
  stackTags:
    APP:  "BRAINY"
    MODULE: "PROJECT"
  environment:
      NODE_ENV: ${file(./serverless.env.yml):${opt:stage}.NODE_ENV}

functions:
  get-by-brand:
    handler: handler.findByBrand
    events:
      - http:
          method: get
          path: /projects/brand/{id}
          cors: true
  get-by-id:
    handler: handler.getById
    events:
      - http:
          method: get
          path: /projects/{id}
          cors: true
  delete:
    handler: handler.deleted
    events:
      - http:
          method: delete
          path: /projects/{id}
          cors: true
  create:
    handler: handler.create
    events:
      - http:
          method: post
          path: /projects
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          method: put
          path: /projects/{id}
          cors: true
  get-by-workspace:
    handler: handler.findByWorkspace
    events:
      - http:
          method: get
          path: /projects/workspace/{id}
          cors: true
