service:
  name: brainy-comment

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  role: arn:aws:iam::970663928408:role/awsLambdaRoleFull
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 7 #
  stackTags:
    APP:  "BRAINY"
    MODULE: "COMMENTS"
  environment:
      NODE_ENV: ${file(./serverless.env.yml):${opt:stage}.NODE_ENV}

functions:
  get-by-id:
    handler: handler.getById
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 #
  delete-comment:
    handler: handler.deletedComment
  delete-thread:
    handler: handler.deletedThread
  undelete-comment:
    handler: handler.undeleteComment
  undelete-thread:
    handler: handler.undeleteThread  
  create:
    handler: handler.create
  answer:
    handler: handler.answer
  update-comment:
    handler: handler.updateComment
  update-thread:
    handler: handler.updateThread
  create-thread-comment:
    handler: handler.createThreadComment
    tags:
    action: POST
