service:
  name: brainy-piece

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  apiGateway: ${file(../../config/serverless.env.yml):${opt:stage}.apiGateway}
  role: arn:aws:iam::970663928408:role/awsLambdaRoleFull
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 7 #
  stackTags:
    APP:  "BRAINY"
    MODULE: "PIECE"
  environment:
      NODE_ENV: ${file(../../config/serverless.env.yml):${opt:stage}.NODE_ENV}

functions:
  create:
    handler: FeedbackPieceFunction.create
    tags:
      action: POST
    events:
      - http:
          method: post
          path: cores/pieces
          authorizer:
            type: CUSTOM
            name: authorizercore
            authorizerId: uydzdd
          cors: true
  createVersion:
    handler: FeedbackPieceFunction.createVersion
    tags:
      action: POST
    events:
      - http:
          method: post
          path: cores/pieces/versions
          authorizer:
            type: CUSTOM
            name: authorizercore
            authorizerId: uydzdd
          cors: true
  deletePiece:
    handler: FeedbackPieceFunction.deletePiece
    tags:
      action: DELETE
    events:
      - http:
          method: delete
          path: cores/pieces/{id}
          authorizer:
            type: CUSTOM
            name: authorizercore
            authorizerId: uydzdd
          cors: true
  get-by-core:
    handler: FeedbackPieceFunction.getByCore
    tags:
      action: GET
    events:
      - http:
          method: get
          path: cores/pieces/{id}
          authorizer:
            type: CUSTOM
            name: authorizercore
            authorizerId: uydzdd
          cors: true

