service:
  name: brainy-core

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  apiGateway: ${file(../../config/serverless.env.yml):${opt:stage}.apiGateway}
  role: arn:aws:iam::970663928408:role/awsLambdaRoleFull
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 12 #
  stackTags:
    APP:  "BRAINY"
    MODULE: "CORE"
  environment:
      NODE_ENV: ${file(../../config/serverless.env.yml):${opt:stage}.NODE_ENV}

functions:
  create:
    handler: handler.create
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 #
    events:
      - http:
          method: post
          path: /workspaces/cores
          authorizer:
            type: CUSTOM
            name: authorizadorwsa
            authorizerId: l9tp37
          cors: true
  get-by-workspace:
    handler: handler.findCoresByWorkspace
    tags:
      action: GET
    events:
      - http:
          method: get
          path: /workspaces/cores
          authorizer:
            type: CUSTOM
            name: authorizadorwsa
            authorizerId: l9tp37
          cors: true
  get-by-id:
    handler: handler.getById
    tags:
      action: GET
    events:
      - http:
          method: get
          path: /workspaces/cores/{id}
          request:
            parameters:
                paths:
                  id: true
          authorizer:
            type: CUSTOM
            name: authorizadorwsa
            authorizerId: l9tp37
          cors: true
  delete:
    handler: handler.deleted
    tags:
      action: DELETE
    events:
      - http:
          method: delete
          path: /workspaces/cores/{id}
          request:
            parameters:
                paths:
                  id: true
          authorizer:
            type: CUSTOM
            name: authorizadorwsa
            authorizerId: l9tp37
          cors: true
  update:
    handler: handler.update
    tags:
      action: PUT
    events:
      - http:
          method: put
          path: /workspaces/cores/{id}
          request:
            parameters:
                paths:
                  id: true
          authorizer:
            type: CUSTOM
            name: authorizadorwsa
            authorizerId: l9tp37
          cors: true
  # listTypes:
  #   handler: handler.listStatus
  #   tags:
  #     action: GET
  # listStatus:
  #   handler: handler.listStatus
  #   tags:
  #     action: GET
