service:
  name: brainy-bucket

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  role: arn:aws:iam::970663928408:role/awsLambdaRoleFull
  environment:
      NODE_ENV: ${file(./serverless.env.yml):${opt:stage}.NODE_ENV}

functions:
  get-signed-url:
    handler: BucketFunction.createSignedUrl
  put-object:
    handler: BucketFunction.putObjectS3
  object-exists:
    handler: BucketFunction.objectExists
    
