
service:
  name: brainy-workspace

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  apiGateway: ${file(../../../config/serverless.env.yml):${opt:stage}.apiGateway}
  role: arn:aws:iam::970663928408:role/awsLambdaRoleFull
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 7 #
  stackTags:
    APP:  "BRAINY"
    MODULE: "WORKSPACES"
  environment:
      NODE_ENV: ${file(../../../config/serverless.env.yml):${opt:stage}.NODE_ENV}

functions:
  get-list-by-user:
    handler: handler.getListByUser
    tags:
      action: GET
    events:
      - http:
          method: post
          path: /workspaces
          authorizer:
            type: CUSTOM
            authorizerId: bh5l1b
          cors: true
  get:
    handler: handler.get
    tags:
      action: GET
    events:
      - http:
          method: get
          path: /workspaces/{id}
          request:
            parameters:
                paths:
                  id: true
          cors: true
  update:
    handler: handler.update
    tags:
      action: PUT
    events:
      - http:
          method: put
          path: /workspaces
          cors: true


  # get-all:
  #   handler: WorkspaceFunction.getAll
  #   tags:
  #     action: GET
  # delete:
  #   handler: WorkspaceFunction.eliminate
  #   tags:
  #     action: DELETE
  # create:
  #   handler: WorkspaceFunction.create
  #   tags:
  #     action: POST
  # update:
  #   handler: WorkspaceFunction.update
  #   tags:
  #     action: PUT

